### ISSUE TITLE
Only runs with ES 5.4.0 not as stated in README with 5.4

### ISSUE THREAD

**Issue by amalic** [MLnick/elasticsearch-vector-scoring#13]
When I use the most current 5.4. version (5.4.3) i got the error message that it only runs with 5.4.0 which is strange since 5.4.0 and 5.4.3 should be API compatible.

Please either fix in code or within the README file.

Steps to reproduce
1. create Dockerfile
```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.3

RUN elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.4.0/elasticsearch-vector-scoring-5.4.0.zip
```
2. Build
`docker build -t es_with_vector-scoring .`

which results in following error
```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.3
 ---> 2ae8547160a7
Step 2/2 : RUN elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.4.0/elasticsearch-vector-scoring-5.4.0.zip
 ---> Running in ca31562f69ae
-> Downloading https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.4.0/elasticsearch-vector-scoring-5.4.0.zip
[=================================================] 100%??
Exception in thread "main" java.lang.IllegalArgumentException: plugin [elasticsearch-vector-scoring] is incompatible with version [5.4.3]; was designed for version [5.4.0]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:428)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:495)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:199)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.4.0/elasticsearch-vector-scoring-5.4.0.zip' returned a non-zero code: 1

```

**Comment by MLnick** [comment]
Hi there - most of this plugin functionality is now supported natively in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

Also see https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch.

See also an update to related Code Pattern on IBM Developer that illustrates a recommendation use case: IBM/elasticsearch-spark-recommender#54
