### ISSUE TITLE
F cannot be cast to java.util.List

### ISSUE THREAD

**Issue by WwwRuiOP** [MLnick/elasticsearch-vector-scoring#16]
Hello , when I use Java code to implement this function, there are some errors:
[indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: NotSerializableExceptionWrapper[class_cast_exception: [F cannot be cast to java.util.List]; }
**The following is the part related to the "payload_vector_score":**
Caused by: NotSerializableExceptionWrapper[class_cast_exception: [F cannot be cast to java.util.List]
	at com.github.mlnick.elasticsearch.script.PayloadVectorScoreScript.<init>(PayloadVectorScoreScript.java:98)
	at com.github.mlnick.elasticsearch.script.PayloadVectorScoreScript.<init>(PayloadVectorScoreScript.java:37)
	at com.github.mlnick.elasticsearch.script.PayloadVectorScoreScript$Factory.newScript(PayloadVectorScoreScript.java:55)
	at org.elasticsearch.script.NativeScriptEngineService.search(NativeScriptEngineService.java:75)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:499)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:491)
	at org.elasticsearch.index.query.QueryShardContext.getSearchScript(QueryShardContext.java:345)
	at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:97)
	... 19 more
**The all errors is following:**
Exception in thread "main" Failed to execute phase [query], all shards failed; shardFailures {[R-SMBGOkSdOwmsCBUtjP3A][contentrecom][0]: RemoteTransportException[[node1][127.0.0.1:9301][indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: NotSerializableExceptionWrapper[class_cast_exception: [F cannot be cast to java.util.List]; }{[JlpGnU20RHGAHDM9hd9kzw][contentrecom][1]: RemoteTransportException[[master][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: ClassCastException[[F cannot be cast to java.util.List]; }{[JlpGnU20RHGAHDM9hd9kzw][contentrecom][2]: RemoteTransportException[[master][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: ClassCastException[[F cannot be cast to java.util.List]; }{[JlpGnU20RHGAHDM9hd9kzw][contentrecom][3]: RemoteTransportException[[master][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: ClassCastException[[F cannot be cast to java.util.List]; }{[JlpGnU20RHGAHDM9hd9kzw][contentrecom][4]: RemoteTransportException[[master][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: ClassCastException[[F cannot be cast to java.util.List]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onInitialPhaseResult(AbstractSearchAsyncAction.java:223)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:58)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:148)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1032)
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$17(TcpTransport.java:1411)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109)
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1409)
	at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1401)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1345)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: RemoteTransportException[[node1][127.0.0.1:9301][indices:data/read/search[phase/query]]]; nested: QueryShardException[script_score: the script could not be loaded]; nested: NotSerializableExceptionWrapper[class_cast_exception: [F cannot be cast to java.util.List];
Caused by: [contentrecom/NBkpXATTSfKlMlpfzgXVSQ] QueryShardException[script_score: the script could not be loaded]; nested: NotSerializableExceptionWrapper[class_cast_exception: [F cannot be cast to java.util.List];
	at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:100)
	at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:137)
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.doToQuery(FunctionScoreQueryBuilder.java:304)
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96)
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313)
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325)
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:599)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:468)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:444)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:252)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: NotSerializableExceptionWrapper[class_cast_exception: [F cannot be cast to java.util.List]
	at com.github.mlnick.elasticsearch.script.PayloadVectorScoreScript.<init>(PayloadVectorScoreScript.java:98)
	at com.github.mlnick.elasticsearch.script.PayloadVectorScoreScript.<init>(PayloadVectorScoreScript.java:37)
	at com.github.mlnick.elasticsearch.script.PayloadVectorScoreScript$Factory.newScript(PayloadVectorScoreScript.java:55)
	at org.elasticsearch.script.NativeScriptEngineService.search(NativeScriptEngineService.java:75)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:499)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:491)
	at org.elasticsearch.index.query.QueryShardContext.getSearchScript(QueryShardContext.java:345)
	at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:97)
	... 19 more

Could you give me some ways to solve this problem? In addition, when I use your method, it works well, the Restful way.

**Comment by WwwRuiOP** [comment]
Hello, in addition, the function is :
FunctionScoreQueryBuilder.FilterFunctionBuilder[] functions = {
                new FunctionScoreQueryBuilder.FilterFunctionBuilder(
                        queryStringQuery(q),
                        scriptFunction(
                                new Script(
                                        ScriptType.INLINE,
                                        "native",
                                        "payload_vector_score",
                                        params)
                        ))
        };
