### ISSUE TITLE
how can I fit it to 5.6.x

### ISSUE THREAD

**Issue by mingzhang96** [MLnick/elasticsearch-vector-scoring#4]
This is a really cool tool but now I am using elasticSearch 5.6.1, you said it can fit to 5.3+ but maybe there are some problem as follow:
```
$ ./elasticsearch-plugin install file:///home/es/elasticsearch-vector-scoring/target/releases/elasticsearch-vector-scoring-5.3.0.zip
-> Downloading file:///home/es/elasticsearch-vector-scoring/target/releases/elasticsearch-vector-scoring-5.3.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: plugin [elasticsearch-vector-scoring] is incompatible with version [5.6.1]; was designed for version [5.3.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:474)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:543)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```
How can I deal with this problem? Thx~

**Comment by MLnick** [comment]
It doesn't support the latest versions of ES as they removed the existing
support for scripts to access term stats & doc vectors.

I will look at updating it for the new mechanism when I have some time. For
now 5.3 works only

**Comment by mingzhang96** [comment]
OK，I am looking forward to a new branch fitting 5.6

**Comment by Canappeco** [comment]
OK, I am looking forward to a new branch fitting to the latest versions of ES.

**Comment by jameskhamil** [comment]
Looking forward to it also! Let me know if I can try to help you

**Comment by MLnick** [comment]
Happy to take PRs if someone has time

**Comment by mobiustech** [comment]
Hey @MLnick - If I were to upgrade to the latest version of ES, how do I go about doing this? Is it even worth it or is there something out there that replaces this?

I meant I can look into upgrading this plugin to latest ES and I just need some hints to start.

**Comment by MLnick** [comment]
I’ll try to take a look this week. What version of ES are you running?

**Comment by MLnick** [comment]
The plugin needs to be refactored a bit to support later ES versions

**Comment by mobiustech** [comment]
6.3.1
Thanks, Nick.
